[application]
default_platform = "desktop"

[bundle]
identifier = "io.github.hacktor.infinite-editor"
publisher = "hacktor"
icon = ["assets/app-icon-256.png", "assets/favicon.ico"]

[web.app]

# HTML title tag content
title = "infinite-editor"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
